### ISSUE TITLE
Missing 'chalk' dependency?

### ISSUE THREAD

**Issue by pdubroy** [caseywebdev/watchy#14]
I just installed v0.6.3, and am getting the following error:

```
> watchy -w README.md,example,doc,src,test -- npm test

module.js:338
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dubroy/dev/cdg/ohm/node_modules/watchy/bin/watchy:36:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

It looks like maybe [chalk](https://www.npmjs.com/package/chalk) is now required, but it isn't listed as a dependency in package.json.

**Comment by caseywebdev** [comment]
Sorry about that, I forgot to clean up an old reference to chalk. Fixed in `0.6.4`, going to yank `0.6.3`.
