### ISSUE TITLE
@atom/watcher problem

### ISSUE THREAD

**Issue by vdegenne** [caseywebdev/watchy#20]
When I `yarn add watchy`, I have this error message

```
$> yarn add watchy -D
yarn add v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠄ @atom/watcher
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
error An unexpected error occurred: "/home/vdegenne/Gits/node/github-fetch-starter/node_modules/@atom/watcher: Command failed.
Exit code: 1
Command: sh
Arguments: -c node --harmony script/helper/gen-compilation-db.js rebuild
Directory: /home/vdegenne/Gits/node/github-fetch-starter/node_modules/@atom/watcher
Output:
module.js:545
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
child_process.js:596
    throw err;
    ^

Error: Command failed: node-gyp rebuild
    at checkExecSyncError (child_process.js:575:11)
    at execFileSync (child_process.js:593:13)
    at Object.<anonymous> (/home/vdegenne/Gits/node/github-fetch-starter/node_modules/@atom/watcher/script/helper/gen-compilation-db.js:21:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)".
info If you think this is a bug, please open a bug report 
```

Do you know what could be the problem ?
my node version is **9.10.0**

**Comment by vdegenne** [comment]
I tried to install watchy^0.8.0 and it works. Only ^0.9.0 specific here

**Comment by caseywebdev** [comment]
I've opened https://github.com/atom/watcher/issues/134 to track the @atom/watcher progress on this.

**Comment by vdegenne** [comment]
@caseywebdev I did as you said `sudo yarn global add node-gyp` (+sudo) but it didn't solve this issue. I mean node-gyp installed like a cream but trying `yarn add watchy -D` produces the same err output. I think I have to install watchy in a ninja sudo fashion but I don't want to because for me installing a local package for an app using root access is counter-logic. And for now `^0.9.0` seems to work nicely so I'll stick with that and wait for a fix or something.
